#spring.application.name=web-socket-req
spring:
  application:
    name: web-socket-req
server:
  port: 8778
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    preferIpAddress: true
